name: Build and Test

on:
  push:
    branches-ignore:
      - main

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0

      - name: Run build with Gradle Wrapper
        run: |
          chmod a+x gradlew
          ./gradlew build

  unittest:
    runs-on: ubuntu-latest
    needs: gradle-build
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0

      - name: Run unit tests with Gradle Wrapper
        run: |
          chmod a+x gradlew
          ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/*

  test-report:
    runs-on: ubuntu-latest
    needs: unittest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: build/test-results

      - name: Publish test report
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            build/test-results/**/*.xml
